### ISSUE TITLE
Does not work when using ${{ github.ref }} as input.tag

### ISSUE THREAD

**Issue by BadIdeaException** [nebula-actions/upload-assets#1]
The following step definition makes the script exit with code 1 on a tag push:
```
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: 
      - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: nebula-actions/upload-assets@v1.0.0
              with:
                  asset-path: whatever
                  tag: ${{ github.ref }}
``` 
This is because `github.ref` includes the prefix `refs/tags/`, so your `GH_RELEASE` variable becomes:
```
https://api.github.com/repos/{author}/{repo}/releases/tags/refs/tags/{tag}
```
But the correct URL as per the [GitHub API docs](https://docs.github.com/en/rest/reference/releases#get-a-release-by-tag-name) should be
```
https://api.github.com/repos/{owner}/{repo}/releases/tags/{tag}
```
